services:
  django-app:
    image: django-image-record-app
    container_name: django_container
    env_file:
      - .env
    networks:
      - record-network
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - record-network

networks:
  record-network:
    external: true